/**
 * Seed Management Module Data
 * 
 * This script generates seed data specifically for the management module.
 * It can be run independently or as part of the main seed script.
 */

import { writeFile, mkdir } from 'fs/promises';
import { join } from 'path';
import {
  generatePermissionAudits,
  generateTrainingCredits,
  generateDocuments,
  generateCommunityResources,
  generateCommunityEvents,
  generateStudents,
  generateTutors,
  generateManagement,
  generateSessions,
  generateClasses
} from '../lib/mockData.js';

async function seedManagement() {
  try {
    console.log('🌱 Starting management module seed...\n');

    // Ensure data directory exists
    const dataDir = join(process.cwd(), 'data');
    try {
      await mkdir(dataDir, { recursive: true });
      console.log('✅ Data directory created/verified\n');
    } catch (error) {
      console.log('ℹ️  Data directory already exists\n');
    }

    // Generate base data needed for management module
    console.log('📊 Generating base data...');
    const students = await generateStudents(20);
    const tutors = await generateTutors(15);
    const management = await generateManagement(5);
    const allUsers = [...students, ...tutors, ...management];
    const sessions = generateSessions(students, tutors, 50);
    const availability = await Promise.all(tutors.map(() => [])); // Simplified for seed
    const classes = generateClasses(tutors, []); // Simplified for seed

    console.log('✅ Base data generated\n');

    // Generate management module data
    console.log('📊 Generating management module data...');
    const permissionAudits = generatePermissionAudits(management, allUsers);
    const trainingCredits = generateTrainingCredits(students, sessions, classes, management);
    const documents = generateDocuments(allUsers);
    const communityResources = generateCommunityResources(allUsers);
    const communityEvents = generateCommunityEvents(management);

    console.log('✅ Management module data generated\n');

    // Write permission audits
    await writeFile(
      join(dataDir, 'permissions-audit.json'),
      JSON.stringify(permissionAudits, null, 2),
      'utf-8'
    );
    console.log(`✅ Created ${permissionAudits.length} permission audits`);

    // Write training credits
    await writeFile(
      join(dataDir, 'training-credits.json'),
      JSON.stringify(trainingCredits, null, 2),
      'utf-8'
    );
    console.log(`✅ Created ${trainingCredits.length} training credits`);

    // Write documents
    await writeFile(
      join(dataDir, 'documents.json'),
      JSON.stringify(documents, null, 2),
      'utf-8'
    );
    console.log(`✅ Created ${documents.length} documents`);

    // Write community resources
    await writeFile(
      join(dataDir, 'community-resources.json'),
      JSON.stringify(communityResources, null, 2),
      'utf-8'
    );
    console.log(`✅ Created ${communityResources.length} community resources`);

    // Write community events
    await writeFile(
      join(dataDir, 'community-events.json'),
      JSON.stringify(communityEvents, null, 2),
      'utf-8'
    );
    console.log(`✅ Created ${communityEvents.length} community events`);

    // Create empty files for data that will be generated by API calls
    const emptyFiles = [
      'optimization-plans.json',
      'progress-reports.json',
      'document-permissions.json',
      'document-sharing.json',
      'document-activities.json',
      'community-activities.json'
    ];

    for (const fileName of emptyFiles) {
      await writeFile(
        join(dataDir, fileName),
        JSON.stringify([], null, 2),
        'utf-8'
      );
      console.log(`✅ Created ${fileName} (empty)`);
    }

    console.log('\n🎉 Management module seeded successfully!\n');
    console.log('📊 Summary:');
    console.log(`   - Permission Audits: ${permissionAudits.length}`);
    console.log(`   - Training Credits: ${trainingCredits.length}`);
    console.log(`   - Documents: ${documents.length}`);
    console.log(`   - Community Resources: ${communityResources.length}`);
    console.log(`   - Community Events: ${communityEvents.length}`);
    console.log('\n');

  } catch (error) {
    console.error('❌ Error seeding management module:', error);
    process.exit(1);
  }
}

// Run if executed directly
seedManagement().catch(console.error);

export default seedManagement;

